name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.x

      - name: Publish project
        run: dotnet publish CpuSim.Web/CpuSim.Web.csproj -c Release -o release --nologo

      - name: Change base-tag
        # GitHub Pages hosts under /<repo-name>/, so we update the base href in index.html
        run: sed -i 's/<base href="\/" \/>/<base href="\/CPU-Simulator\/" \/>/g' release/wwwroot/index.html

      - name: Add .nojekyll
        # Prevents GitHub Pages from ignoring files starting with underscores (critical for Blazor)
        run: touch release/wwwroot/.nojekyll

      - name: Copy index.html to 404.html
        # Hack to handle SPA routing on GitHub Pages
        run: cp release/wwwroot/index.html release/wwwroot/404.html

      - name: Commit and Push to gh-pages branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: release/wwwroot
          branch: gh-pages
